//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutReader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Config : global::System.Configuration.ApplicationSettingsBase {
        
        private static Config defaultInstance = ((Config)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Config())));
        
        public static Config Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elizarovo2Enabled {
            get {
                return ((bool)(this["Elizarovo2Enabled"]));
            }
            set {
                this["Elizarovo2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ElizarovoSimaticEnabled {
            get {
                return ((bool)(this["ElizarovoSimaticEnabled"]));
            }
            set {
                this["ElizarovoSimaticEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BrickEnabled {
            get {
                return ((bool)(this["BrickEnabled"]));
            }
            set {
                this["BrickEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StreamLuxEnabled {
            get {
                return ((bool)(this["StreamLuxEnabled"]));
            }
            set {
                this["StreamLuxEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MerkurEnabled {
            get {
                return ((bool)(this["MerkurEnabled"]));
            }
            set {
                this["MerkurEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.8.15")]
        public string ServerIp {
            get {
                return ((string)(this["ServerIp"]));
            }
            set {
                this["ServerIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5129")]
        public int ElizarovoPort {
            get {
                return ((int)(this["ElizarovoPort"]));
            }
            set {
                this["ElizarovoPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5128")]
        public int BrickPort {
            get {
                return ((int)(this["BrickPort"]));
            }
            set {
                this["BrickPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public int StreamLuxPort {
            get {
                return ((int)(this["StreamLuxPort"]));
            }
            set {
                this["StreamLuxPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ElizarovoInterval {
            get {
                return ((int)(this["ElizarovoInterval"]));
            }
            set {
                this["ElizarovoInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int BrickInterval {
            get {
                return ((int)(this["BrickInterval"]));
            }
            set {
                this["BrickInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int ElizarovoSimaticInterval {
            get {
                return ((int)(this["ElizarovoSimaticInterval"]));
            }
            set {
                this["ElizarovoSimaticInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150000")]
        public int StreamLuxInterval {
            get {
                return ((int)(this["StreamLuxInterval"]));
            }
            set {
                this["StreamLuxInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29125194")]
        public int Merkur1Id {
            get {
                return ((int)(this["Merkur1Id"]));
            }
            set {
                this["Merkur1Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21701")]
        public int Merkur1Port {
            get {
                return ((int)(this["Merkur1Port"]));
            }
            set {
                this["Merkur1Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TeplosetEnabled {
            get {
                return ((bool)(this["TeplosetEnabled"]));
            }
            set {
                this["TeplosetEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120000")]
        public int TeplosetInterval {
            get {
                return ((int)(this["TeplosetInterval"]));
            }
            set {
                this["TeplosetInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3600000")]
        public int VzletInterval {
            get {
                return ((int)(this["VzletInterval"]));
            }
            set {
                this["VzletInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VzletEnabled {
            get {
                return ((bool)(this["VzletEnabled"]));
            }
            set {
                this["VzletEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string VzletComPort {
            get {
                return ((string)(this["VzletComPort"]));
            }
            set {
                this["VzletComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900000")]
        public int MerkurInterval {
            get {
                return ((int)(this["MerkurInterval"]));
            }
            set {
                this["MerkurInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.22.100")]
        public string LiftWaterIp {
            get {
                return ((string)(this["LiftWaterIp"]));
            }
            set {
                this["LiftWaterIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LiftWaterEnabled {
            get {
                return ((bool)(this["LiftWaterEnabled"]));
            }
            set {
                this["LiftWaterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int LiftWaterInterval {
            get {
                return ((int)(this["LiftWaterInterval"]));
            }
            set {
                this["LiftWaterInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.22.150")]
        public string OwenLiftWaterIp {
            get {
                return ((string)(this["OwenLiftWaterIp"]));
            }
            set {
                this["OwenLiftWaterIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OwenLiftWaterEnabled {
            get {
                return ((bool)(this["OwenLiftWaterEnabled"]));
            }
            set {
                this["OwenLiftWaterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int OwenLiftWaterInterval {
            get {
                return ((int)(this["OwenLiftWaterInterval"]));
            }
            set {
                this["OwenLiftWaterInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GeoKiselevaEnabled {
            get {
                return ((bool)(this["GeoKiselevaEnabled"]));
            }
            set {
                this["GeoKiselevaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int GeoKiselevaInterval {
            get {
                return ((int)(this["GeoKiselevaInterval"]));
            }
            set {
                this["GeoKiselevaInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.8.99")]
        public string GeoKiselevaIp {
            get {
                return ((string)(this["GeoKiselevaIp"]));
            }
            set {
                this["GeoKiselevaIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21703")]
        public int GeoKiselevaPort {
            get {
                return ((int)(this["GeoKiselevaPort"]));
            }
            set {
                this["GeoKiselevaPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int KNSInterval {
            get {
                return ((int)(this["KNSInterval"]));
            }
            set {
                this["KNSInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.8.99")]
        public string KNSIP {
            get {
                return ((string)(this["KNSIP"]));
            }
            set {
                this["KNSIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KNSEnabled {
            get {
                return ((bool)(this["KNSEnabled"]));
            }
            set {
                this["KNSEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.8.86")]
        public string StreamLuxIP {
            get {
                return ((string)(this["StreamLuxIP"]));
            }
            set {
                this["StreamLuxIP"] = value;
            }
        }
    }
}
